### ISSUE TITLE
Pod install.

### ISSUE THREAD

**Issue by Dzionis** [abdullahselek/SwiftyNotifications#2]
[!] Unable to find a specification for `SwiftyNotifications (~> 0.2)`

///
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'XXX' do
pod 'SwiftyNotifications', '~>0.2'
end

**Comment by abdullahselek** [comment]
Hi @Dzionis, you can remove you pod master and call setup again. This is something related with CocoaPods [Repairing-Our-Broken-Specs-Repository](http://blog.cocoapods.org/Repairing-Our-Broken-Specs-Repository/)

`pod repo remove master` and `pod setup`
