### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [abdullahselek/SwiftyNotifications#3]
Good day @abdullahselek  I am a graphic designer and i would like to contribute to your good project by designing a logo for free. I first need your permission Sir so i can start my design. Thanks and best regards!

-Tobaloidee

**Comment by abdullahselek** [comment]
Hi @Tobaloidee, thanks for your offer. Yes you can create a logo for free, may I learn which license do you use for logo?

**Comment by Tobaloidee** [comment]
Hi Sir..i use Creative Commons 4.0 

Should i start my design?

**Comment by abdullahselek** [comment]
Yes please, you can start.

**Comment by Tobaloidee** [comment]
here Sir, still open for modification..i hope you like it

![pres-02](https://user-images.githubusercontent.com/36028424/41958359-68deb08c-7a1c-11e8-9e34-21e719c32b91.png)

**Comment by abdullahselek** [comment]
I like it 👍 I prefer orange logo and label.

**Comment by Tobaloidee** [comment]
Im glad that you liked it! will make a PR now and upload the logo and put it in the readme :)

**Comment by abdullahselek** [comment]
Sounds good, thanks!

**Comment by Tobaloidee** [comment]
Here's the PR #4 Sir, Thanks again!

**Comment by Tobaloidee** [comment]
Hi @abdullahselek  here you can download all the design versions of the logo

[DOWNLOAD](https://drive.google.com/drive/u/1/folders/122T7gX2CZTpTgClcRdz_LCFlJw3dg5ln)

![gifgif](https://user-images.githubusercontent.com/36028424/42614476-b375b236-85d8-11e8-98cb-222a31f04d84.gif)

**Comment by abdullahselek** [comment]
Thank you @Tobaloidee

**Comment by Tobaloidee** [comment]
Sir @abdullahselek  i made some adjustments with the logo and it is updated in the download link I provided.. Thanks a lot!
