### ISSUE TITLE
iPhone X Notch blocking content

### ISSUE THREAD

**Issue by nissaba** [abdullahselek/SwiftyNotifications#5]
![Capture d’écran, le 2019-11-13 à 17 01 09](https://user-images.githubusercontent.com/3584506/68808243-51966480-0637-11ea-9d76-768e655c3a9b.png)
 as shown in the image the notch is blocking part of the content.

**Comment by abdullahselek** [comment]
Hi @nissaba thanks for your interest, problem has been fixed on version `0.5.4.1`.
